version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - davidgarciab
    assignees:
      - davidgarciab
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    ignore:
      # Ignore some updates to the 'vue' package
      - dependency-name: "vue"
        # Ignore only new versions for 3.x and 4.x
        versions: ["3.x", "4.x"]
      - dependency-name: "webpack"
        # Ignore only new versions for 5.x and 6.x
        versions: ["5.x", "6.x"]        
